### ISSUE TITLE
When will the dataset be released and available for public download？

### ISSUE THREAD

**Issue by 980202006** [Multi-Singer/Multi-Singer.github.io#1]
Hello, the effect of your Multi-Singer paper is so amazing, it can even be used on the speaker of unseen. I want to know how long the data set corresponding to this paper will be available for download.

**Comment by Multi-Singer** [comment]
Data is coming soon. Researchers who are interested in applying for this dataset, please send an formal application email at help_multisinger@163.com. After passing through data preparation procedures, we will reply to each application in order.
